import Head from "next/head";
import { Card, H1 } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4">
        <H1>Creative Coding</H1>
        <div className="grid sm:grid-cols-4">
          <Card>
            <>Testar</>
          </Card>
        </div>
      </main>
    </div>
  );
}
